name: marvelous
description: Marvel demo app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Keep this section alphabetized
  bloc_test: ^9.1.0
  crypto: ^3.0.2
  dio: ^4.0.6
  envied: ^0.2.4
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Keep this section alphabetized
  build_runner:
  envied_generator:
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  json_serializable: ^6.5.3

flutter:
